# Generated by Django 4.1.2 on 2022-12-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_categories_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
