# Generated by Django 4.1.2 on 2022-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
