# Generated by Django 4.1.2 on 2023-01-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_carusel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carusel',
            name='carouselImg',
        ),
        migrations.RemoveField(
            model_name='carusel',
            name='title',
        ),
        migrations.CreateModel(
            name='ImagesOfCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='img', max_length=100)),
                ('carouselImg', models.ImageField(upload_to='')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyApp.carusel')),
            ],
        ),
    ]
