# Generated by Django 4.1.2 on 2023-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_carusel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carusel',
            name='img',
        ),
        migrations.AddField(
            model_name='carusel',
            name='carusel',
            field=models.CharField(default='Слайдер', max_length=100),
        ),
    ]
