# Generated by Django 4.1.2 on 2023-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_remove_carusel_img_carusel_carusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='news', max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carusel',
            options={'verbose_name': 'Слайдер(Стопка)', 'verbose_name_plural': 'Слайдеры(Стопка)'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категории товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='imagesofcarusel',
            options={'verbose_name': 'Фото для слайдеров', 'verbose_name_plural': 'Фото для слайдеров'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Файлы сайта (Видео)', 'verbose_name_plural': 'Файлы сайта (Видео)'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
