# Generated by Django 4.1.2 on 2023-01-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_news_alter_carusel_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
